### numpy.mean() ###
    numpy.mean() 函数返回数组中元素的算术平均值。 如果提供了轴，则沿其计算。
    算术平均值是沿轴的元素的总和除以元素的数量。

In [3]:
import numpy as np
a=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print(np.mean(a))
print(np.mean(a,axis = 0)) #纵轴
print(np.mean(a,axis = 1))#横轴

[[1 2 3]
 [3 4 5]
 [4 5 6]]
3.6666666666666665
[2.66666667 3.66666667 4.66666667]
[2. 4. 5.]


### numpy.zeros() ###
    创建指定大小的数组，数组元素以 0 来填充

In [5]:
import numpy as np
#默认为浮点型
x = np.zeros(4)
print(x)
y = np.zeros((4,2))#里面是(4,2)
print(y)

#设置类型为整数
z = np.zeros(4, dtype = np.int)
print(z)

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[0 0 0 0]
