### apply ###
只能对DataFrame对象进行操作，指针对里面的每个元素利用这个函数

In [13]:
import numpy as np
import pandas as pd
data = np.arange(0,16).reshape(4,4)
print(data)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [14]:
data = pd.DataFrame(data,columns = ['0','1','2','3'])
print(data)

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15


In [18]:
def f(x):
    return x-1
print(data.ix[:,['0','1']].apply(f))

    0   1
0  -1   0
1   3   4
2   7   8
3  11  12


C:\Users\16538\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  app.launch_new_instance()
