In [4]:
train_test_split用法：把一个数据集按照想要的比例分成两部分。
比如：对数据集A和对应的biao'q

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
X,y = np.arange(10).reshape((5,2)), range(5)
X

In [5]:
list(y)

[0, 1, 2, 3, 4]

In [15]:
X_train, X_test = train_test_split(X, test_size=0.2, random_state=72)
#random_state：伪随机数发生器，只要该种子（seed）相同，产生的随机数序列就是相同的
print("训练集:\n{0}".format(X_train))
print("测试集:\n{0}".format(X_test))

训练集:
[[8 9]
 [4 5]
 [6 7]
 [0 1]]
测试集:
[[2 3]]
